const compBuilds = {
    builds:[
        {
            cpu: 'Intel 4690K',
            cpuCooler: 'Corsair h100i Platinum',
            motherboard: 'MSI z97 Gaming 5',
            memory: 'Hyper Fury 16GB 1600 CAS 10',
            storage: '1TB 2.5in SSD',
            videocard: 'MSI 1660 Super',
            compcase: 'Phantek Entoo Evolv X',
            powersupply: 'Seasonic 850 Prime Gold',
            os: 'Windows 10 Pro',
            fan: 'Corsair ML RGB',
            monitor: '2 Samsung 24in ',
            keyboard: 'Corsair K70',
            mouse: 'Logitech G903',
        },
        {
            cpu: 'Intel 9900KS',
            cpuCooler: 'Corsair h110i Platinum',
            motherboard: 'MSI z370 Ace',
            memory: 'G.Skill Trident Z RGB 32 GB 3200 CAS 16',
            storage: '1TB M.2 SSD',
            videocard: 'EVGA 2080 Super Black edition',
            compcase: 'Phantek p400A',
            powersupply: 'Seasonic 850 Prime Platinum',
            os: 'Windows 10 Home',
            fan: 'Corsair LL RGB',
            monitor: 'ROG 32in 1440p 144hz',
            keyboard: 'Corsair K90',
            mouse: 'Glorious PC Gaming Race MODEL O',
        },
        {
            cpu: 'AMD Ryzen 5 3600',
            cpuCooler: 'Wraith Stealth',
            motherboard: 'ASRock x570 Taichi',
            memory: 'G.Skill Trident Z NEO 16 GB 3400 CAS 16',
            storage: '1TB M.2 SSD',
            videocard: 'Radeon RX 5700xt Sapphire Nitro+',
            compcase: 'NZXT 510',
            powersupply: 'EVGA SuperNova G3 750 Gold',
            os: 'Windows 10 Home',
            fan: 'Corsair LL RGB',
            monitor: 'ROG 27in 1440p 144hz',
            keyboard: 'Logitech G Pro',
            mouse: 'Logitech G502 lightspeed',
        },
        {
            cpu: 'AMD Ryzen 9 3900x',
            cpucooler: 'be quiet! Dark Rock Pro 4',
            motherboard: 'Asus ROG Crosshair VIII Hero',
            memory: 'Corsair Vengeance RGB Pro 64 GB 3600 CAS 14',
            storage: ' 2 TB Corsair MP600 Force Series Gen4 M.2',
            videocard: 'Asus ROG Strix Gaming OC RTX 2080Ti',
            compcase: 'Lian Li PC-O11 Dynamic',
            powersupply: 'SeaSonic PRIME Ultra Titanium 1000w',
            os: 'Windows 10 Home',
            fan: 'Noctua NF-F12 PWM chromax',
            monitor: 'LG Ultrawide 32in 1440p 144hz',
            keyboard: 'Razer BlackWidow Chroma',
            mouse: 'Razer Viper Ultimate',
        },
        {
            cpu: 'AMD 3700x',
            cpucooler: 'Custom open water cooling loop',
            motherboard: 'MSI MEG X570 GODLIKE',
            memory: 'Corsair Dominator Platinum 32 GB 3600 CAS 16',
            storage: '2 TB Corsair MP600 Force Series Gen4 M.2',
            videocard: 'MSI GAMING X TRIO RTX 2080Ti',
            compcase: 'InWIn 905',
            powersupply: 'SeaSonic PRIME Ultra Titanium 1000w',
            os: 'Windows 10 Home',
            fan: 'Corsair ML RGB',
            monitor: 'LG Ultrawide 32in 1440p 144hz',
            keyboard: 'Ducky One 2 Mini',
            mouse: 'Logitech G Pro Wireless',
        },
    ]
}

export default compBuilds